version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - laravel_db

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  laravel_db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
