version: "3.9"

services:
  basic_node_app:
    build:
      context: .
    volumes:
      - ./uploads:/var/www/html/uploads
    expose:
      - "6001"
    networks:
      - basic_node_app_network
      
  basic_node_app_2:
    build:
      context: .
    volumes:
      - ./uploads:/var/www/html/uploads
    expose:
      - "6001"
    networks:
      - basic_node_app_network
      
  basic_node_app_3:
    build:
      context: .
    volumes:
      - ./uploads:/var/www/html/uploads
    expose:
      - "6001"
    networks:
      - basic_node_app_network
      
  basic_node_app_4:
    build:
      context: .
    volumes:
      - ./uploads:/var/www/html/uploads
    expose:
      - "6001"
    networks:
      - basic_node_app_network
      
  nginx:
    image: nginx:latest
    ports:
      - "8005:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - basic_node_app
      - basic_node_app_2
      - basic_node_app_3
      - basic_node_app_4
    networks:
      - basic_node_app_network

  basicNodeMysqlDB:
    image: mysql:latest
    container_name: basicNodeMysqlDB
    ports:
      - "3506:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: workshop_devops
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - /var/www/basic_node_app/db/mysql:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - basic_node_app_network

  basicNodeMongoDB:
    image: mongo:latest
    container_name: basicNodeMongoDB
    ports:
      - "29017:27017"
    volumes:
      - /var/www/basic_node_app/db/mongo:/data/db
    networks:
      - basic_node_app_network

networks:
  basic_node_app_network:
    driver: bridge
