version: '3.7'
services:
  php_app1:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"

  php_app2:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"

  php_app3:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"

  php_app4:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"

  php_app5:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php_app1
      - php_app2
      - php_app3
      - php_app4
      - php_app5

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/mnt/c/Users/mypho/Desktop/basic_node_app/db/grafana:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
