global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['103.191.240.173:9100']